export interface ImageGenerator {
  id: string;
  name: string;
  provider: string;
  model: string;
  description: string;
  pricePerImage: number;
  quality: "low" | "medium" | "high" | "ultra";
  speed: "slow" | "medium" | "fast" | "instant";
  supportsImgToImg: boolean;
  supportsReference: boolean;
  style: "realistic" | "artistic" | "3d" | "any";
  free: boolean;
  badge?: string;
  apiKey: string;
  replicateModel?: string;
}

export interface VideoGenerator {
  id: string;
  name: string;
  provider: string;
  description: string;
  pricePer5s: number;
  pricePer10s: number;
  quality: "low" | "medium" | "high" | "ultra";
  maxDuration: number;
  supportsImgToVideo: boolean;
  badge?: string;
  url: string;
}

export const IMAGE_GENERATORS: ImageGenerator[] = [
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro 🍌",
    provider: "NanoPhoto.ai",
    model: "nano-banana-pro",
    description: "Google Imagen 3 — 95%+ cohérence personnage, jusqu'à 8 photos de référence",
    pricePerImage: 0.15,
    quality: "ultra",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "95% Cohérence",
    apiKey: "NANOBANA_API_KEY",
  },
  {
    id: "nano-banana",
    name: "Nano Banana 🍌",
    provider: "NanoPhoto.ai",
    model: "nano-banana",
    description: "Google Imagen 3.1 Flash — rapide, 14 refs max, meilleur rapport qualité/prix",
    pricePerImage: 0.10,
    quality: "high",
    speed: "fast",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "14 refs",
    apiKey: "NANOBANA_API_KEY",
  },
  {
    id: "ideogram-character",
    name: "Ideogram Character ⭐",
    provider: "Fal.ai",
    model: "fal-ai/ideogram/character",
    description: "🎭 MEILLEUR pour cohérence personnage — passe ta photo → même visage garanti",
    pricePerImage: 0.08,
    quality: "ultra",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "Cohérence visage",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "instant-character",
    name: "Instant Character",
    provider: "Fal.ai",
    model: "fal-ai/instant-character",
    description: "🎭 Contrôle d'identité fort — photo référence → personnage cohérent",
    pricePerImage: 0.05,
    quality: "high",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "Identité forte",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "minimax-subject",
    name: "MiniMax Subject Ref",
    provider: "Fal.ai",
    model: "fal-ai/minimax/image-01/subject-reference",
    description: "🎭 Référence sujet — maintient l'apparence du personnage sur toutes les images",
    pricePerImage: 0.04,
    quality: "high",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "Photo → Scène",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "dalle3-hd",
    name: "DALL-E 3 HD",
    provider: "OpenAI",
    model: "dall-e-3",
    description: "Meilleure compréhension des prompts complexes, cohérence narrative",
    pricePerImage: 0.080,
    quality: "high",
    speed: "medium",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: false,
    badge: "Recommandé",
    apiKey: "OPENAI_API_KEY",
  },
  {
    id: "dalle3-standard",
    name: "DALL-E 3 Standard",
    provider: "OpenAI",
    model: "dall-e-3",
    description: "Bonne qualité, moins cher que HD",
    pricePerImage: 0.040,
    quality: "medium",
    speed: "medium",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: false,
    apiKey: "OPENAI_API_KEY",
  },
  {
    id: "flux-schnell",
    name: "FLUX Schnell",
    provider: "Replicate",
    model: "black-forest-labs/flux-schnell",
    description: "Gratuit, ultra rapide, bonne qualité. Pas img2img.",
    pricePerImage: 0.003,
    quality: "medium",
    speed: "instant",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: true,
    badge: "Gratuit",
    apiKey: "REPLICATE_API_TOKEN",
    replicateModel: "black-forest-labs/flux-schnell",
  },
  {
    id: "flux-dev",
    name: "FLUX Dev",
    provider: "Replicate",
    model: "black-forest-labs/flux-dev",
    description: "Haute qualité, img2img disponible — cohérence personnages",
    pricePerImage: 0.025,
    quality: "high",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "img2img",
    apiKey: "REPLICATE_API_TOKEN",
    replicateModel: "black-forest-labs/flux-dev",
  },
  {
    id: "flux-pro",
    name: "FLUX Pro",
    provider: "Replicate / Fal.ai",
    model: "black-forest-labs/flux-1.1-pro",
    description: "Qualité maximale, détails ultra précis, img2img avancé",
    pricePerImage: 0.055,
    quality: "ultra",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "Ultra",
    apiKey: "FAL_API_KEY",
    replicateModel: "black-forest-labs/flux-1.1-pro",
  },
  {
    id: "sdxl",
    name: "Stable Diffusion XL",
    provider: "Replicate",
    model: "stability-ai/sdxl",
    description: "Classique, très populaire, img2img excellent pour cohérence",
    pricePerImage: 0.008,
    quality: "medium",
    speed: "medium",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    apiKey: "REPLICATE_API_TOKEN",
    replicateModel: "stability-ai/sdxl",
  },
  {
    id: "playground-v3",
    name: "Playground v3",
    provider: "Replicate",
    model: "playgroundai/playground-v2.5-1024px-aesthetic",
    description: "Excellent pour style artistique et animé, très esthétique",
    pricePerImage: 0.012,
    quality: "high",
    speed: "fast",
    supportsImgToImg: false,
    supportsReference: false,
    style: "artistic",
    free: false,
    apiKey: "REPLICATE_API_TOKEN",
    replicateModel: "playgroundai/playground-v2.5-1024px-aesthetic",
  },
  {
    id: "ideogram-v2",
    name: "Ideogram v2",
    provider: "Replicate",
    model: "ideogram-ai/ideogram-v2",
    description: "Excellent pour Pixar 3D et animation, gestion texte dans images",
    pricePerImage: 0.080,
    quality: "ultra",
    speed: "medium",
    supportsImgToImg: false,
    supportsReference: false,
    style: "3d",
    free: false,
    badge: "Pixar 3D",
    apiKey: "REPLICATE_API_TOKEN",
    replicateModel: "ideogram-ai/ideogram-v2",
  },
  {
    id: "fal-flux-schnell",
    name: "Fal.ai FLUX Schnell",
    provider: "Fal.ai",
    model: "fal-ai/flux/schnell",
    description: "Quasi gratuit, 4 étapes, résultat en 1-2 secondes",
    pricePerImage: 0.001,
    quality: "medium",
    speed: "instant",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: true,
    badge: "Quasi gratuit",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "fal-flux-dev",
    name: "Fal.ai FLUX Dev",
    provider: "Fal.ai",
    model: "fal-ai/flux/dev",
    description: "Haute qualité, img2img, plus rapide que Replicate",
    pricePerImage: 0.025,
    quality: "high",
    speed: "fast",
    supportsImgToImg: true,
    supportsReference: true,
    style: "any",
    free: false,
    badge: "img2img",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "fal-recraft",
    name: "Fal.ai Recraft v3",
    provider: "Fal.ai",
    model: "fal-ai/recraft-v3",
    description: "Spécialisé illustration et style animé vectoriel — excellent Pixar",
    pricePerImage: 0.022,
    quality: "ultra",
    speed: "medium",
    supportsImgToImg: false,
    supportsReference: false,
    style: "3d",
    free: false,
    badge: "Illustration",
    apiKey: "FAL_API_KEY",
  },
  {
    id: "together-flux-schnell",
    name: "Together.ai FLUX Schnell",
    provider: "Together.ai",
    model: "black-forest-labs/FLUX.1-schnell",
    description: "Gratuit avec compte, très rapide, bon pour tester",
    pricePerImage: 0.000,
    quality: "medium",
    speed: "instant",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: true,
    badge: "100% Gratuit",
    apiKey: "TOGETHER_API_KEY",
  },
  {
    id: "hf-free",
    name: "HuggingFace FLUX Free",
    provider: "HuggingFace",
    model: "black-forest-labs/FLUX.1-dev",
    description: "Entièrement gratuit via HuggingFace Inference API",
    pricePerImage: 0.000,
    quality: "medium",
    speed: "slow",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: true,
    badge: "Gratuit HF",
    apiKey: "HUGGINGFACE_API_KEY",
  },
  {
    id: "stability-core",
    name: "Stability AI Core",
    provider: "Stability AI",
    model: "stable-image/generate/core",
    description: "API officielle Stable Diffusion, bonne qualité, pas cher",
    pricePerImage: 0.003,
    quality: "medium",
    speed: "fast",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: false,
    badge: "SD Officiel",
    apiKey: "STABILITY_API_KEY",
  },
  {
    id: "stability-ultra",
    name: "Stability AI Ultra",
    provider: "Stability AI",
    model: "stable-image/generate/ultra",
    description: "Qualité maximale SD, excellent pour personnages détaillés",
    pricePerImage: 0.008,
    quality: "high",
    speed: "medium",
    supportsImgToImg: false,
    supportsReference: false,
    style: "any",
    free: false,
    apiKey: "STABILITY_API_KEY",
  },
];

export const VIDEO_GENERATORS: VideoGenerator[] = [
  {
    id: "kling-15-std",
    name: "Kling AI 1.5 Standard",
    provider: "Kling AI",
    description: "Meilleur pour animation de personnages, mouvements naturels",
    pricePer5s: 0.28,
    pricePer10s: 0.56,
    quality: "high",
    maxDuration: 10,
    supportsImgToVideo: true,
    badge: "Recommandé",
    url: "https://klingai.com",
  },
  {
    id: "kling-15-pro",
    name: "Kling AI 1.5 Pro",
    provider: "Kling AI",
    description: "Qualité cinématique, idéal pour scènes épiques",
    pricePer5s: 0.70,
    pricePer10s: 1.40,
    quality: "ultra",
    maxDuration: 10,
    supportsImgToVideo: true,
    badge: "Cinéma",
    url: "https://klingai.com",
  },
  {
    id: "seedance-1",
    name: "SeedDance 1.0",
    provider: "ByteDance",
    description: "Excellent pour chorégraphies et danses, très fluide",
    pricePer5s: 0.35,
    pricePer10s: 0.70,
    quality: "high",
    maxDuration: 10,
    supportsImgToVideo: true,
    badge: "Nouveau",
    url: "https://seedance.ai",
  },
  {
    id: "runway-gen3",
    name: "Runway Gen-3 Alpha",
    provider: "Runway ML",
    description: "Fidèle à l'image de référence, transitions fluides",
    pricePer5s: 0.25,
    pricePer10s: 0.50,
    quality: "high",
    maxDuration: 10,
    supportsImgToVideo: true,
    url: "https://runwayml.com",
  },
  {
    id: "luma-ray2",
    name: "Luma Ray 2",
    provider: "Luma AI",
    description: "Rendu 3D photoréaliste, excellent pour décors",
    pricePer5s: 0.42,
    pricePer10s: 0.84,
    quality: "ultra",
    maxDuration: 9,
    supportsImgToVideo: true,
    badge: "3D",
    url: "https://lumalabs.ai",
  },
  {
    id: "minimax-video",
    name: "MiniMax Video-01",
    provider: "MiniMax",
    description: "Excellent rapport qualité/prix, cohérence personnages",
    pricePer5s: 0.18,
    pricePer10s: 0.36,
    quality: "medium",
    maxDuration: 6,
    supportsImgToVideo: true,
    badge: "Économique",
    url: "https://minimax.io",
  },
  {
    id: "wan-replicate",
    name: "Wan 2.1 (Replicate)",
    provider: "Wan / Replicate",
    description: "Open-source, bon marché, img2video depuis Replicate",
    pricePer5s: 0.08,
    pricePer10s: 0.16,
    quality: "medium",
    maxDuration: 10,
    supportsImgToVideo: true,
    badge: "Pas cher",
    url: "https://replicate.com",
  },
];

export function getDefaultImageGenerator(): string {
  if (typeof window !== "undefined") {
    return localStorage.getItem("sf_default_img_gen") || "nano-banana-pro";
  }
  return "nano-banana-pro";
}

export function setDefaultImageGenerator(id: string) {
  if (typeof window !== "undefined") {
    localStorage.setItem("sf_default_img_gen", id);
  }
}

export function getDefaultVideoGenerator(): string {
  if (typeof window !== "undefined") {
    return localStorage.getItem("sf_default_vid_gen") || "kling-15-std";
  }
  return "kling-15-std";
}

export function setDefaultVideoGenerator(id: string) {
  if (typeof window !== "undefined") {
    localStorage.setItem("sf_default_vid_gen", id);
  }
}
