"use client";

import { useState, useEffect, use } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import toast from "react-hot-toast";
import { ArrowLeft, Volume2, Loader2, Copy, Music, Mic } from "lucide-react";

interface Scene {
  id: string;
  sceneNumber: number;
  narration?: string;
  dialogue?: string;
  soundDesign?: string;
  audioPrompt?: string;
  voiceProvider?: string;
  voiceUrl?: string;
}

export default function AudioPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const [scenes, setScenes] = useState<Scene[]>([]);
  const [episodeTitle, setEpisodeTitle] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => { fetchData(); }, [id]);

  async function fetchData() {
    try {
      const res = await fetch(`/api/episodes/${id}`);
      if (res.status === 401) { router.push("/login"); return; }
      const data = await res.json();
      setEpisodeTitle(data.title);
      setScenes(data.scenes || []);
    } finally {
      setLoading(false);
    }
  }

  function copy(text: string) {
    navigator.clipboard.writeText(text);
    toast.success("Copied!");
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="mb-6">
        <Link href={`/episodes/${id}/editor`} className="flex items-center gap-2 text-gray-400 hover:text-white text-sm mb-4 transition-colors w-fit">
          <ArrowLeft className="w-4 h-4" /> Back to Editor
        </Link>
        <h1 className="text-3xl font-bold text-white flex items-center gap-3">
          <Volume2 className="w-7 h-7 text-orange-400" /> Audio Planning
        </h1>
        <p className="text-gray-400 mt-1">{episodeTitle}</p>
      </div>

      <div className="mb-6 p-4 bg-orange-900/20 border border-orange-600/30 rounded-xl">
        <p className="text-orange-300 text-sm">
          🎙 Audio plans are generated by the AI pipeline. Connect ElevenLabs, Suno AI, or other providers to generate actual audio files.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-purple-400" /></div>
      ) : scenes.length === 0 ? (
        <div className="text-center py-16 bg-[#13131a] border border-dashed border-[#2a2a3e] rounded-2xl">
          <Volume2 className="w-12 h-12 text-gray-600 mx-auto mb-4" />
          <p className="text-gray-400">Run the episode pipeline first to generate audio plans</p>
          <Link href={`/episodes/${id}/editor`} className="mt-4 inline-flex items-center gap-2 px-5 py-2.5 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-xl transition-all">
            Go to Editor
          </Link>
        </div>
      ) : (
        <div className="space-y-4">
          {scenes.map(scene => (
            <div key={scene.id} className="bg-[#13131a] border border-[#2a2a3e] rounded-xl p-5">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-white text-lg">Scene {scene.sceneNumber}</h3>
                {scene.voiceProvider && (
                  <span className="text-xs px-2 py-0.5 bg-orange-600/20 border border-orange-600/30 rounded-full text-orange-300">
                    🎙 {scene.voiceProvider}
                  </span>
                )}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {scene.narration && (
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-xs text-gray-500 uppercase tracking-wide flex items-center gap-1"><Mic className="w-3 h-3" /> Narrator</p>
                      <button onClick={() => copy(scene.narration!)} className="text-xs text-blue-400 hover:text-blue-300 flex items-center gap-1"><Copy className="w-3 h-3" /> Copy</button>
                    </div>
                    <div className="bg-[#1e1e2e] border border-blue-600/30 rounded-lg p-3">
                      <p className="text-sm text-blue-200">{scene.narration}</p>
                    </div>
                  </div>
                )}
                {scene.dialogue && (
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-xs text-gray-500 uppercase tracking-wide flex items-center gap-1"><Mic className="w-3 h-3" /> Dialogue</p>
                      <button onClick={() => copy(scene.dialogue!)} className="text-xs text-purple-400 hover:text-purple-300 flex items-center gap-1"><Copy className="w-3 h-3" /> Copy</button>
                    </div>
                    <div className="bg-[#1e1e2e] border border-purple-600/30 rounded-lg p-3">
                      <p className="text-sm text-purple-200">{scene.dialogue}</p>
                    </div>
                  </div>
                )}
                {scene.soundDesign && (
                  <div>
                    <p className="text-xs text-gray-500 uppercase tracking-wide mb-1 flex items-center gap-1"><Music className="w-3 h-3" /> Sound Design</p>
                    <div className="bg-[#1e1e2e] border border-[#2a2a3e] rounded-lg p-3">
                      <p className="text-sm text-gray-300">{scene.soundDesign}</p>
                    </div>
                  </div>
                )}
                {scene.audioPrompt && (
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-xs text-gray-500 uppercase tracking-wide">Audio Direction</p>
                      <button onClick={() => copy(scene.audioPrompt!)} className="text-xs text-orange-400 hover:text-orange-300 flex items-center gap-1"><Copy className="w-3 h-3" /> Copy</button>
                    </div>
                    <div className="bg-[#1e1e2e] border border-orange-600/20 rounded-lg p-3">
                      <p className="text-sm text-gray-300">{scene.audioPrompt}</p>
                    </div>
                  </div>
                )}
              </div>
              {scene.voiceUrl && (
                <div className="mt-3">
                  <audio controls src={scene.voiceUrl} className="w-full" />
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
