import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { prisma } from "@/lib/db/prisma";
import { getCurrentUser } from "@/lib/auth";
import { buildScenePromptWithDNA, generateVisualDNA } from "@/lib/agents/visualDNAAgent";
import type { VisualDNA } from "@/lib/agents/visualDNAAgent";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { id } = await params;

    const episode = await prisma.episode.findFirst({
      where: { id, series: { userId: user.id } },
      include: {
        series: {
          include: { characters: true, environments: true },
        },
      },
    });
    if (!episode) return NextResponse.json({ error: "Episode not found" }, { status: 404 });

    const { series } = episode;

    // STEP 1: Auto-generate visual DNA for any character missing it
    const dnaGenerated = [];
    for (const char of series.characters) {
      if (!char.visualDNA) {
        const dna = await generateVisualDNA({
          character: {
            name: char.name,
            physicalDescription: char.physicalDescription,
            outfit: char.outfit,
            personality: char.personality,
            referenceImageUrl: char.referenceImageUrl,
          },
          visualStyle: series.visualStyle,
        });

        await prisma.character.update({
          where: { id: char.id },
          data: { visualDNA: JSON.stringify(dna) },
        });

        char.visualDNA = JSON.stringify(dna);
        dnaGenerated.push(char.name);
      }
    }

    // Build character list with DNA
    const characters = series.characters.map(c => ({
      name: c.name,
      consistencyPrompt: c.consistencyPrompt,
      visualDNA: c.visualDNA ? JSON.parse(c.visualDNA) as VisualDNA : null,
    }));

    const scenes = await prisma.scene.findMany({
      where: { episodeId: id },
      orderBy: { sceneNumber: "asc" },
    });

    const results = [];

    for (const scene of scenes) {
      try {
        const sceneCharNames: string[] = JSON.parse(scene.charactersJson || "[]");

        const matchedEnv = series.environments.find(e =>
          scene.location?.toLowerCase().includes(e.name.toLowerCase())
        ) || series.environments[0];

        const prompt = buildScenePromptWithDNA({
          characters,
          sceneCharacters: sceneCharNames,
          location: scene.location || "",
          environmentDescription: matchedEnv?.description || scene.location || "",
          action: scene.action || "",
          emotion: scene.emotion || "",
          camera: scene.camera || "medium shot",
          visualStyle: series.visualStyle,
          format: episode.format,
          lighting: matchedEnv?.lighting || undefined,
          mood: matchedEnv?.mood || undefined,
        });

        const size = episode.format === "9:16" ? "1024x1792" : "1792x1024";

        const response = await openai.images.generate({
          model: "dall-e-3",
          prompt: prompt.slice(0, 4000),
          n: 1,
          size: size as "1024x1024" | "1024x1792" | "1792x1024",
          quality: "hd",
        });

        const imageUrl = (response.data ?? [])[0]?.url;
        if (imageUrl) {
          await prisma.scene.update({ where: { id: scene.id }, data: { imageUrl } });
          results.push({ sceneNumber: scene.sceneNumber, success: true, imageUrl });
        }
      } catch (err) {
        results.push({
          sceneNumber: scene.sceneNumber,
          success: false,
          error: err instanceof Error ? err.message : "Failed",
        });
      }
    }

    return NextResponse.json({
      success: true,
      total: scenes.length,
      generated: results.filter(r => r.success).length,
      dnaAutoGenerated: dnaGenerated,
      results,
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : "Failed";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
